//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UESRPG_Character_Manager.CharacterComponents {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PowerDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PowerDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UESRPG_Character_Manager.CharacterComponents.PowerDescriptions", typeof(PowerDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This power may be activated once per encounter as a free action. The character gains a level of fatigue, but doubles their Stamina
        ///for 30 seconds (6 rounds). The character can choose to extend the duration, but each round they do so incurs another level of fatigue..
        /// </summary>
        public static string AdrenalineRush {
            get {
                return ResourceManager.GetString("AdrenalineRush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each Dunmer is capable of invoking a guardian spirit of one of their ancestors and can, through the use of the Cast Magic action, bring that spirit into the Mundus to aid them. The spirit counts as a ghost (see the Inhabitants of Tamriel supplement) which, if killed, is sent back to whence it came. Otherwise, the spirit persists for half an hour until it must leave.
        ///
        ///If the Dunmer attempts to invoke the spirit again within a week of the last time, they must make an opposed Willpower test against the spiri [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AncestorGuardian {
            get {
                return ResourceManager.GetString("AncestorGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosmer can speak to, and understand the speech of, animals. How exactly this functions is left to the GM’s discretion, though it is recommended the GM call for a Perception test when the Bosmer encounters the speech of an unfamiliar animal..
        /// </summary>
        public static string BeastTongue {
            get {
                return ResourceManager.GetString("BeastTongue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperials speak with a small bit of the power and majesty of the Emperors. They may choose to use their Willpower as the base for any Charm, Command, or Deceive skill tests..
        /// </summary>
        public static string VoiceOfTheEmperor {
            get {
                return ResourceManager.GetString("VoiceOfTheEmperor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters with this power gain a +10 bonus to Intimidate tests made when using the Intimidating Shout action, and a +10 bonus to their first attack test against any targets who failed the opposed Willpower test imposed by Intimidating Shout within the next two rounds after the use of the action..
        /// </summary>
        public static string WarCry {
            get {
                return ResourceManager.GetString("WarCry", resourceCulture);
            }
        }
    }
}
