//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UESRPG_Character_Manager.CharacterComponents {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TraitDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraitDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UESRPG_Character_Manager.CharacterComponents.TraitDescriptions", typeof(TraitDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character can breathe water, and ignores the skill cap placed on his combat rolls by his Athletics skill when fighting in water..
        /// </summary>
        public static string Amphibious {
            get {
                return ResourceManager.GetString("Amphibious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A character with this trait can see normally even in areas with total darkness, and never takes penalties for acting in areas with dim or no lighting..
        /// </summary>
        public static string DarkSight {
            get {
                return ResourceManager.GetString("DarkSight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters with this trait have a chance to resist diseases. Whenever the character would be infected by a common disease, roll a d100. If the roll is less than or equal to X, the character doesn’t get the disease..
        /// </summary>
        public static string DiseaseResistance {
            get {
                return ResourceManager.GetString("DiseaseResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character is larger or heavier than other creatures within its same size category, and thus there is more force behind each of its blows. Add X to the character’s Damage Bonus..
        /// </summary>
        public static string HeavyHitter {
            get {
                return ResourceManager.GetString("HeavyHitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character is immune to any of the effects of the thing specified in parenthesis. The character may have multiple instances of this trait for different effects *..
        /// </summary>
        public static string Immunity {
            get {
                return ResourceManager.GetString("Immunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters with this trait have more magicka than usual. The size of their Magicka Pool is increased by X% of its base. If the character would receive this trait twice, combine the X values..
        /// </summary>
        public static string PowerWell {
            get {
                return ResourceManager.GetString("PowerWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argonians receive a -10 penalty to Charm tests made to interact with non-Argonians. However, Observe tests made to try to distinguish their motives are made with a -10 penalty..
        /// </summary>
        public static string RacialInscrutable {
            get {
                return ResourceManager.GetString("RacialInscrutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altmer ignore penalties to Willpower tests made to resist paralysis..
        /// </summary>
        public static string RacialMentalStrength {
            get {
                return ResourceManager.GetString("RacialMentalStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosmer never suffer untrained penalties worse than -10 when using bows or crossbows..
        /// </summary>
        public static string RacialNaturalArchers {
            get {
                return ResourceManager.GetString("RacialNaturalArchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperials increase their Stamina by 1..
        /// </summary>
        public static string RacialStarOfTheWest {
            get {
                return ResourceManager.GetString("RacialStarOfTheWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters with this trait are resistant to a certain damage type, such as rending damage, or magic damage. The damage type is specified in *. If the character suffers damage after armor mitigation with the damage type *, reduce that damage by X% (round up) before calculating the effects of the damage. Instances of magic resistance stack with specific damage type resistances. If a character has both this trait and the weakness trait for the same damage type, then simply ignore the smaller value and treat th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Resistance {
            get {
                return ResourceManager.GetString("Resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character is larger or heavier than other creatures within its same size category, and thus can take more punishment. Increase the character’s Health by X% of its base value (round down)..
        /// </summary>
        public static string Tough {
            get {
                return ResourceManager.GetString("Tough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters with this trait are weak to a certain damage type, such as rending damage, fire damage, magic damage, and so forth. The damage type is specified in *. If the character suffers damage after armor mitigation with the damage type *, increase that damage by X% (round up) before calculating the effects of the damage. Instances of magic weakness stack with specific damage type weakness.
        ///
        ///If a character has both this trait and the resistance trait for the same damage type, then simply ignore the small [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Weakness {
            get {
                return ResourceManager.GetString("Weakness", resourceCulture);
            }
        }
    }
}
